Cancer_Type=$1
Working_Directory="/diskmnt/Projects/Users/wliang/Pancan_Fusion/20_Driver3/Final"
SampleList="/diskmnt/Projects/Users/wliang/Pancan_Fusion/20_Driver3/IntersectSampleList/${Cancer_Type}.sample.txt"
Summary="/diskmnt/Projects/Users/wliang/Pancan_Fusion/20_Driver3/Summary/${Cancer_Type}.exclusive.summary.txt"

echo -e "Sample\tCancer_Type\tAlteration_of_DriverGene" > ${Working_Directory}/${Cancer_Type}.sample_wise.final.driver.txt

#cat ${Summary} | awk -F "\t" '{OFS="\t"; if ($3!="NA" && $4!="NA" && $5=="NA") print $1, $2, "Mutation_and_Fusion"; else if ($3!="NA" && $4=="NA" && $5=="NA") print $1, $2, "Mutation_Only"; else if ($3=="NA" && $4 !="NA" && $5=="NA") print $1, $2, "Fusion_Only"; else if ($3!="NA" && $4=="NA" && $5!="NA") print $1, $2, "Mutation_and_DriverMutation"; else if ($3!="NA" && $4!="NA" && $5!="NA") print $1, $2, "Mutation_Fusion_and_DriverMutation"; else if ($3=="NA" && $4!="NA" && $5!="NA") print $1, $2, "Fusion_and_DriverMutation"; else if ($3=="NA" && $4=="NA" && $5!="NA") print $1, $2, "DriverMuation_Only"}' | awk -F "\t" -v x=${Cancer_Type} 'NR==FNR{a[$1]=$2"\t"$3;next}{OFS="\t"; if (substr($1,1,12) in a) print substr($1,1,12), a[substr($1,1,12)]; else print substr($1,1,12), x, "No_Driver_Alteration"}' - ${SampleList} >> ${Working_Directory}/${Cancer_Type}.sample_wise.final.driver.txt

cat ${Summary} | awk -F "\t" '{OFS="\t"; if ($3!="NA" && $4!="NA" && $5=="NA") print $1, $2, "Mutation_and_Fusion"; else if ($3!="NA" && $4=="NA" && $5=="NA") print $1, $2, "Mutation_Only"; else if ($3=="NA" && $4 !="NA" && $5=="NA") print $1, $2, "Fusion_Only"; else if ($3!="NA" && $4=="NA" && $5!="NA") print $1, $2, "DriverMutation_Only"; else if ($3!="NA" && $4!="NA" && $5!="NA") print $1, $2, "DriverMutation_and_Fusion"; else if ($3=="NA" && $4!="NA" && $5!="NA") print $1, $2, "DriverMutation_and_Fusion"; else if ($3=="NA" && $4=="NA" && $5!="NA") print $1, $2, "DriverMutation_Only"}' | awk -F "\t" -v x=${Cancer_Type} 'NR==FNR{a[$1]=$2"\t"$3;next}{OFS="\t"; if (substr($1,1,12) in a) print substr($1,1,12), a[substr($1,1,12)]; else print substr($1,1,12), x, "No_Driver_Alteration"}' - ${SampleList} >> ${Working_Directory}/${Cancer_Type}.sample_wise.final.driver.txt
